### ISSUE TITLE
Could not copy the file BackgroundWorker.js because it was not found. 

### ISSUE THREAD

**Issue by bv5396** [mingyaulee/Blazor.BrowserExtension#152] opened 2024-07-04 02:50 UTC
Hello,

I changed my background page to bg.js in manifest and everything was working fine for many weeks but all of a sudden I am getting errors,

Could not copy the file BackgroundWorker.js because it was not found. 

It take me to,

    <Copy SourceFiles="@(_BrowserExtension_Project_BuildOutput_BrowserExtension_FilesToCopy)"
          DestinationFolder="$(_BrowserExtension_Project_BuildOutput_BrowserExtension_Directory)\%(_BrowserExtension_Project_BuildOutput_BrowserExtension_FilesToCopy.CopyToRelativeDirectory)"
          SkipUnchangedFiles="true" />

It is searching BackgroundWorker.js but I already changed that name to bg.js in the manifest file. 

Can you please let me know how to solve this? All my projects are showing the same error message.

Thanks

**Comment by mingyaulee** [comment] 2024-07-04 09:17
This is caused by the new feature for background worker generation from C# to JS in `v1.5.0`. A workaround for this is to change the PackageReference version in your project to `v1.4.2` until a fix is issued.

**Comment by mingyaulee** [comment] 2024-07-04 21:13
This has been resolved in `v1.5.1`.

**Closed by mingyaulee** 2024-07-04 21:13 UTC
