### ISSUE TITLE
Add support for remote authentication / MSAL.js?

### ISSUE THREAD

**Issue by johnW-ret** [mingyaulee/Blazor.BrowserExtension#52] opened 2023-01-26 02:08 UTC
I created [an issue](https://github.com/dotnet/aspnetcore/issues/46203) in the dotnet/aspnetcore repo bringing up the idea of browser extension support for remote authentication / `Microsoft.Identity.Web. Given this is a separate project not supported by the aspnetcore team, I was a bit skeptical that it wouldn't get closed, but I wanted to hear their feedback first. I linked to a somewhat working implementation on [a fork of mine](https://github.com/johnW-ret/aspnetcore/commit/94ff7ccc44616546b25043f690195f63ba324458). The official repo makes calls to MSAL.js, and the general gist to add browser extension support is to wrap those calls with [chrome.identity.launchWebAuthFlow](https://developer.chrome.com/docs/extensions/reference/identity/#method-launchWebAuthFlow).

The current fork is a bit buggy still, likely due to my current implementation's dependency on virtual routing. I may be able to iron this out.

I wanted to bring up the discussion of what the best way to incorporate authentication would be from a framework and architecture standpoint.

The [Authentication.Msal](https://github.com/dotnet/aspnetcore/tree/main/src/Components/WebAssembly/Authentication.Msal/src) library ships its own ``AuthenticationService.ts`` to use with WebAssembly.Authentication's ``RemoteAuthenticationService``, so it might be possible to produce a library that layers on top of WebAssembly.Authentication like Authentication.Msal does. The advantage of this implementation is interop with existing Msal APIs. I have two Blazor projects, one extension and one hosted SWA, that share a RCL.

If this is possible and desired, the question would be where should the source live? I wouldn't mind spinning up a Blazor.BrowserExtension.Authentication or Blazor.BrowserExtension.Authentication.Msal, but I wouldn't mind working in this repository as well, so I'd like to hear what the direction for this project is, any guidelines, etc.

**Comment by mingyaulee** [comment] 2023-01-27 20:05
It is good that you have asked about it. I am not familiar with MSAL so I can't really help out much with implementation of it. At to the question of whether to implement it in this repository or in your own, I think it is up to you to decide, but I am open to accepting pull request to keep the source into this repository.

**Comment by johnW-ret** [comment] 2023-01-28 02:22
Actually, I was dealing with some outdated nuget cache issues, and it does work even with the default non-physical routing - only when loaded unpacked and in built with Debug config. Any idea on where best to investigate?

**Comment by mingyaulee** [comment] 2023-01-28 07:41
Can you explain more on the issue that you are having?

**Comment by johnW-ret** [comment] 2023-01-28 20:13
The flow completes successfully in Debug, but on Release and when either artifact is uploaded to the Chrome store, upon starting the login process, the authentication popup appears briefly then closes, and an ```Unchecked runtime.lastError: Authorization page could not be loaded.``` error is reported in the console.

With my preliminary web searching, it seems likely that it's an issue with permissions, since it doesn't happen with the same exact source on Debug. I was hoping to maybe be pointed toward what documentation might enumerate and explain the differences between the project configurations in regards to Blazor WASM and this extension package.

**Comment by mingyaulee** [comment] 2023-01-28 20:43
From what I know, this package does not have any difference when publishing in different build configurations. It does sound weird that it works in debug configuration. Maybe what you can try it is to see if it works too when you publish using release configuration and load it locally without publishing to the Chrome store. If it does then it might be some kind of bug from Chrome because it only happens when loading the same extension package from the store.

**Comment by johnW-ret** [comment] 2023-01-28 21:23
I apologize for the false alarm. The rule of finding the answer yourself shortly after you post about it relative to how long you were trying before you make a post reigns supreme 🙂.

Switching the build configuration changes the unique extension ID, and my redirect URI in my app configuration and Azure portal had been pointing to the Debug build's ID.

I will keep you updated to the timeline of making this source available on GH. Ideally, it should support all remote authentication providers, so I'd develop with an architecture that supports multiple providers in mind, but I will likely only focus on MSAL specifically as it is specifically implemented in dotnet/aspnetcore and is currently the only one that pertains to me.

**Comment by mingyaulee** [comment] 2023-01-28 21:28
That's great, you have found the cause of the problem. It's a good strategy you have so I hope more projects can benefit from your work too when it's ready.

**Comment by mingyaulee** [comment] 2023-04-27 04:48
Closing issue as clarified

**Closed by mingyaulee** 2023-04-27 04:48 UTC
